# -------------------------------------------------------------------------------------
#
# Copyright (c) 2021, WSO2 Inc. (http://www.wso2.com). All Rights Reserved.
#
# This software is the property of WSO2 Inc. and its suppliers, if any.
# Dissemination of any information or reproduction of any material contained
# herein in any form is strictly forbidden, unless permitted by WSO2 expressly.
# You may not alter or remove any copyright or other notice from copies of this content.
#
# --------------------------------------------------------------------------------------

trigger:
  - none

pr:
  branches:
    include:
    - main

pool:
  vmImage: 'ubuntu-latest'

resources:
  repositories:
    - repository: code
      type: github
      name: VimukthiPerera/Testgrid
      ref: main
      endpoint: VimukthiPerera
    - repository: templates
      type: github
      name: VimukthiPerera/TestSnykPublicRepo
      ref: main
      endpoint: VimukthiPerera

jobs:
  - job: Checkouty
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - checkout: code
  - template: cd-pipelines/templates/static-scan-terraform.yaml@templates
